apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: galaxy-api
  name: galaxy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galaxy-api
  strategy: {}
  template:
    metadata:
      labels:
        app: galaxy-api
    spec:
      containers:
      - args:
        - run
        - api
        env:
        - name: GALAXY_DB_URL
          value: postgres://galaxy:galaxy@postgres:5432/galaxy
        - name: GALAXY_RABBITMQ_HOST
          value: rabbitmq
        - name: GALAXY_RABBITMQ_PASSWORD
          value: galaxy
        - name: GALAXY_SECRET_KEY
          value: secret
        - name: GALAXY_AWS_ACCESS_KEY_ID
          value: ''
        - name: GALAXY_AWS_SECRET_ACCESS_KEY
          value: ''
        - name: GALAXY_AWS_STORAGE_BUCKET_NAME
          value: ''
        image: mansong/galaxy:latest
        imagePullPolicy: "Always"
        name: galaxy-api
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always